######################################################################
# Automatically generated by qmake (3.0) Fri Jan 29 18:35:28 2016
######################################################################

TEMPLATE = app
TARGET = hello
INCLUDEPATH += .

# Input
SOURCES += hello.cpp
