######################################################################
# Automatically generated by qmake (3.0) Fri Jan 29 18:35:28 2016
######################################################################

TEMPLATE = app
TARGET = find_domains
INCLUDEPATH += .

# Input
SOURCES += find_domains.cpp
